-- Database setup removed - using mock data instead
-- This file is kept for reference but not used

-- If you want to add a database later, you can use these table definitions:
-- CREATE TABLE waitlist_signups (
--   id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
--   first_name TEXT NOT NULL,
--   last_name TEXT NOT NULL,
--   email TEXT UNIQUE NOT NULL,
--   company TEXT NOT NULL,
--   job_title TEXT NOT NULL,
--   company_size TEXT,
--   industry TEXT,
--   phone TEXT,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
-- );
